# Generated by Django 4.0.1 on 2022-01-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='beginning',
            field=models.DateTimeField(default=None, null=True, verbose_name='Beginning time'),
        ),
        migrations.AddField(
            model_name='booking',
            name='ending',
            field=models.DateTimeField(default=None, null=True, verbose_name='Ending time'),
        ),
    ]
