# Generated by Django 4.0.1 on 2022-01-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, verbose_name='Name')),
                ('type', models.IntegerField(choices=[(1, 'budgetary'), (2, 'standart'), (3, 'business')], verbose_name='Type')),
            ],
        ),
    ]
