# Generated by Django 4.0.1 on 2022-01-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='city_location',
            field=models.IntegerField(choices=[(1, 'Moscow'), (2, 'SPB'), (3, 'Krasnodar')], default=1),
            preserve_default=False,
        ),
    ]
