# Generated by Django 4.0.1 on 2022-01-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_city_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='address',
            field=models.CharField(db_index=True, default=1, max_length=50, verbose_name='address'),
            preserve_default=False,
        ),
    ]
